$(document).ready(function(){
  $("#profilejquery").hide();
  $("#profile").click(function(){
      $("#profilejquery").toggle(1000);
  });
});
$(document).ready(function(){
  $("#resumejquery").hide();
  $("#resume").click(function(){
      $("#resumejquery").toggle(1000);
  });
});
